### ISSUE TITLE
Catch an event for each note when scheduling?

### ISSUE THREAD

**Issue by deemaagog** [danigb/sample-player#5]
Could you please clarify, is there a way for catching  start and stop events for each note when using schedule method?

**Comment by danigb** [comment]
The scheduling capabilities of this library are rather basic. There is no way to add listeners to those events, although adding the "onend" could be fairly easy (not the same with "onstart" because there's no native support for that even in the WebAudio specification)

**Comment by deemaagog** [comment]
Thanks. What approach can be used for highlighting current note  while playing?

**Comment by danigb** [comment]
The standard approach is this one: https://www.html5rocks.com/en/tutorials/audio/scheduling/

You can use something like [waaclock](https://github.com/sebpiq/WAAClock) or [tone.js](https://github.com/Tonejs/Tone.js)... There are plenty of libraries...

Good luck!
